export const ADD_CARDS_FROM_SERVER = 'ADD_CARDS_FROM_SERVER';
export const HAVE_ERROR = 'HAVE_ERROR';
export const ADD_CARD = 'ADD_CARD';
export const REMOVE_CARDS = 'REMOVE_CARDS';
export const CHANGE_CARD = 'CHANGE_CARD';
export const CARD_TO_REMOVE = 'CARD_TO_REMOVE';
export const CHANGE_VIEW_CHECKBOX = 'CHANGE_VIEW_CHECKBOX';